# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
no: # Replace with a single onen95464 username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
: # Replace with a single username
: # Replace with a single  username
: # Replace with a single username
custom: # Replace with up to 1 custom sponsorship e.g., ['link1'/and clone'link2'] back to all
